;;; uv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uv.el

(autoload 'uv-sync-background "uv"
"Run `uv sync' silently in background." t)
(autoload 'uv-repeat-run "uv"
"Repeat the last `uv run' command with its arguments." t)
(autoload 'uv-repeat-tool-run "uv"
"Repeat the last `uv tool run' command with its arguments." t)
 (autoload 'uv-tool-run "uv" nil t)
(autoload 'uv-cache-clean "uv"
"Clean the uv cache." t)
(autoload 'uv-cache-prune "uv"
"Prune the uv cache." t)
(register-definition-prefixes "uv" '("uv-"))


;;; End of scraped data

(provide 'uv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uv-autoloads.el ends here
